/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Model.Personal.Usuario;

/**
 *
 * @author Wendy
 */
public class Menu extends javax.swing.JFrame {

    public Menu(Usuario user) {
        initComponents();
        lblUser.setText(user.getUsername());
        switch(user.getRol()){
            case "Administrador":
                this.menuEmpleado.setEnabled(true);
                this.menuConsultorio.setEnabled(true);
                this.menuConsulta.setEnabled(true);
                this.menuCita.setEnabled(false);
                this.menuFactura.setEnabled(false);
                this.menuPaciente.setEnabled(false);
                this.adminI.setEnabled(true);
                this.adminO.setEnabled(true);
                this.adminP.setEnabled(true);
                this.menuCheck.setEnabled(false);
                break;
            case "Recepcionista":
                this.menuEmpleado.setEnabled(false);
                this.menuConsultorio.setEnabled(false);
                this.menuConsulta.setEnabled(false);
                this.menuCita.setEnabled(true);
                this.menuFactura.setEnabled(false);
                this.menuPaciente.setEnabled(true);
                this.adminI.setEnabled(false);
                this.adminO.setEnabled(false);
                this.adminP.setEnabled(false);
                this.menuCheck.setEnabled(true);
                break;
            case "Medico":
                this.menuEmpleado.setEnabled(false);
                this.menuConsultorio.setEnabled(false);
                this.menuConsulta.setEnabled(true);
                this.menuCita.setEnabled(false);
                this.menuFactura.setEnabled(false);
                this.menuPaciente.setEnabled(false);
                this.adminI.setEnabled(false);
                this.adminO.setEnabled(false);
                this.adminP.setEnabled(false);
                this.menuCheck.setEnabled(false);
                break;
            case "Cajero":
                this.menuEmpleado.setEnabled(false);
                this.menuConsultorio.setEnabled(false);
                this.menuConsulta.setEnabled(false);
                this.menuCita.setEnabled(false);
                this.menuFactura.setEnabled(true);
                this.menuPaciente.setEnabled(false);
                this.adminI.setEnabled(false);
                this.adminO.setEnabled(false);
                this.adminP.setEnabled(false);
                this.menuCheck.setEnabled(false);
                break;
            case "Enfermero":
                this.menuEmpleado.setEnabled(true);
                this.menuConsultorio.setEnabled(true);
                this.menuConsulta.setEnabled(true);
                this.menuCita.setEnabled(false);
                this.menuFactura.setEnabled(false);
                this.menuPaciente.setEnabled(false);
                this.adminI.setEnabled(false);
                this.adminO.setEnabled(false);
                this.adminP.setEnabled(false);
                this.menuCheck .setEnabled(true);
                break;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuClinica = new javax.swing.JMenu();
        menuEmpleado = new javax.swing.JMenuItem();
        menuConsultorio = new javax.swing.JMenuItem();
        menuPaciente = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenuItem();
        menuCita = new javax.swing.JMenuItem();
        menuFactura = new javax.swing.JMenuItem();
        menuCheck = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        adminP = new javax.swing.JMenuItem();
        adminI = new javax.swing.JMenuItem();
        adminO = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("BIENVENIDO");

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUser.setText("[Usuario]");

        menuClinica.setText("Clínica");

        menuEmpleado.setText("Empleados");
        menuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadoActionPerformed(evt);
            }
        });
        menuClinica.add(menuEmpleado);

        menuConsultorio.setText("Consultorios");
        menuClinica.add(menuConsultorio);

        menuPaciente.setText("Pacientes");
        menuClinica.add(menuPaciente);

        menuConsulta.setText("Consultas");
        menuClinica.add(menuConsulta);

        menuCita.setText("Citas");
        menuClinica.add(menuCita);

        menuFactura.setText("Facturas");
        menuClinica.add(menuFactura);

        menuCheck.setText("Check-In/Out");
        menuClinica.add(menuCheck);

        jMenuBar1.add(menuClinica);

        menuReportes.setText("Reportes");

        adminP.setText("Producción");
        menuReportes.add(adminP);

        adminI.setText("Ingresos");
        menuReportes.add(adminI);

        adminO.setText("Ocupación");
        menuReportes.add(adminO);

        jMenuBar1.add(menuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser)
                    .addComponent(jLabel1))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadoActionPerformed
        // TODO add your handling code here:
        mEmpleados mEmp = new mEmpleados();
        mEmp.setVisible(true);
    }//GEN-LAST:event_menuEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem adminI;
    private javax.swing.JMenuItem adminO;
    private javax.swing.JMenuItem adminP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenuItem menuCheck;
    private javax.swing.JMenuItem menuCita;
    private javax.swing.JMenu menuClinica;
    private javax.swing.JMenuItem menuConsulta;
    private javax.swing.JMenuItem menuConsultorio;
    private javax.swing.JMenuItem menuEmpleado;
    private javax.swing.JMenuItem menuFactura;
    private javax.swing.JMenuItem menuPaciente;
    private javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables
}
